{% set version = "2.0.4" %}

package:
  name: photospline
  version: '{{ version }}'

source:
  url: https://github.com/cnweaver/photospline/archive/v{{ version }}.tar.gz
  sha256: 0a675ffe27e1d99fe482cdd7692320d6852c11c9a63de7e710ba075989e0bfb5

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('photospline', max_pin='x.x') }}

requirements:
  build:
    - cmake >=3.1
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy >=1.7
    - suitesparse
    - cfitsio
  run:
    - python
    - {{ pin_compatible('numpy', lower_bound='1.7') }}
    - suitesparse
    - cfitsio

test:
  imports:
    - photospline

about:
  home: https://github.com/cnweaver/photospline
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: 'Tensor product B-spline fitting and evaluation'
  description: |
    Detector response to a high-energy physics process is often estimated by
    Monte Carlo simulation. For purposes of data analysis, the results of this
    simulation are typically stored in large multi-dimensional histograms,
    which can quickly become unwieldy in terms of size or numerically
    problematic due to unfilled bins or interpolation artifacts. Photospline is
    a library that uses the penalized spline technique to efficiently compute,
    store, and evaluate B-spline representations of such tables.
  dev_url: https://github.com/cnweaver/photospline

extra:
  recipe-maintainers:
    - jvansanten
