{% set version = "2.2.0" %}

package:
  name: photospline
  version: {{ version }}

source:
  url: https://github.com/icecube/photospline/archive/v{{ version }}.tar.gz
  sha256: 81f79b42fd63e12c13cc369fb5c6ef356389f7c7aaa10a584aae2e22dba79ccf

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('photospline', max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake >=3.1
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - suitesparse
    - cfitsio
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - suitesparse
    - cfitsio

test:
  imports:
    - photospline
  source_files:
    - test
  requires:
    - coreutils
  commands:
    - timeout 10 python test/test_fit.py || (stat=$?; test $stat -eq 124 || exit $stat)
    - photospline-config --help
    - photospline-eval test/test_data/test_spline_3d_nco.fits 0 0 0
    - photospline-inspect test/test_data/test_spline_3d_nco.fits

about:
  home: https://github.com/icecube/photospline
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: Tensor product B-spline fitting and evaluation
  description: |
    Detector response to a high-energy physics process is often estimated by
    Monte Carlo simulation. For purposes of data analysis, the results of this
    simulation are typically stored in large multi-dimensional histograms,
    which can quickly become unwieldy in terms of size or numerically
    problematic due to unfilled bins or interpolation artifacts. Photospline is
    a library that uses the penalized spline technique to efficiently compute,
    store, and evaluate B-spline representations of such tables.
  dev_url: https://github.com/icecube/photospline

extra:
  recipe-maintainers:
    - jvansanten
